services:

  db:
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "movie_match"
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    networks:
      - db

  server:
    build:
      context: "./server"
    volumes:
      - "./server/config.development.yaml:/opt/movie-match/config.yaml:ro"
      - "server_data_posters:/opt/movie-match/posters"
    ports:
      - "6445:6445"
    depends_on:
      - db
    networks:
      - db

  app:
    build:
      context: "./app"
    environment:
      MOVIEMATCH_API_SERVER_BASE_URL: "http://192.168.127.22:6445/"
    ports:
      - "8080:80"

networks:
  db:

volumes:
  db_data:
  server_data_posters:

