services:

  db:
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "movie_match"
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    networks:
      - db

#  app:
#    image: golang:1.19.5-alpine3.17
#    working_dir: /app
#    volumes:
#      - ./:/app:ro
#    command: 'go run ./cmd/server'

networks:
  db:

volumes:
  db_data:
