name: Build and Publish

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build-and-publish-docker-image:
    name: Build docker images and publish
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: "linux/amd64"

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ### app

      - name: Build app image and publish as specific tag
        uses: docker/build-push-action@v4
        if: ${{ github.ref_type == 'tag' }}
        with:
          context: ./app
          tags: "ghcr.io/${{ github.repository }}-app:${{ github.ref_name }}"
          push: true

      - name: Build app image and publish as latest
        uses: docker/build-push-action@v4
        if: ${{ github.ref_type != 'tag' }}
        with:
          context: ./app
          tags: "ghcr.io/${{ github.repository }}-app:latest"
          push: ${{ github.ref == 'refs/heads/main' }}

      ### server

      - name: Build server image and publish as specific tag
        uses: docker/build-push-action@v4
        if: ${{ github.ref_type == 'tag' }}
        with:
          context: ./server
          tags: "ghcr.io/${{ github.repository }}-server:${{ github.ref_name }}"
          push: true

      - name: Build server image and publish as latest
        uses: docker/build-push-action@v4
        if: ${{ github.ref_type != 'tag' }}
        with:
          context: ./server
          tags: "ghcr.io/${{ github.repository }}-server:latest"
          push: ${{ github.ref == 'refs/heads/main' }}
